Repository KKUMTEUL/KKUMTEUL-frontend, pull requests merged in 2024-10, with the labels that each got.

#32 Refactor: 자녀 성향 진단 결과 반환값 구조 변경
  src/components/survey/Interest.tsx
  src/components/survey/MbtiFifth.tsx
  src/components/survey/MbtiFirst.tsx
  src/components/survey/MbtiForth.tsx
  src/components/survey/MbtiSecond.tsx
  src/components/survey/MbtiThird.tsx
  src/pages/Survey/index.tsx
Labels: 🚀 Refactor

#34 Feat: 유저 정보 조회 api 매핑
  src/pages/MyPage/index.tsx
  src/pages/MyPageCreateChildProfile/index.tsx
  src/pages/MyPageDetailChildProfile/index.tsx
  src/pages/MyPageEditUserProfile/index.tsx
Labels: ✨ Feat

#43 Feat: switch childprofile
  src/pages/Main/index.tsx
Labels: ✨ Feat

#44 Feat: 마이페이지 api 매핑 (자녀 프로필 삭제, 유저 탈퇴)
  src/pages/MyPage/index.tsx
  src/pages/MyPageEditUserProfile/index.tsx
  src/pages/MyPageManageChildProfile/index.tsx
Labels: ✨ Feat

#41 Feat: 도서 전체 목록 api 매핑
  package-lock.json
  package.json
  src/pages/BookList/index.tsx
Labels: ✨ Feat

#50 Feat: 추천책 반환 구조 변경 및 도서 이미지 포맷팅
  src/pages/Main/index.tsx
Labels: 🚀 Refactor

#53 Feat: 메인페이지 인기책 목록 추가
  src/pages/Main/index.tsx
Labels: ✨ Feat

#42 Feat: API 매핑 (메인페이지, MBTI 설문)
  src/components/survey/Interest.tsx
  src/components/surveyresult/ProgressLine.tsx
  src/pages/ChildPersonalityHistoryDetail/index.tsx
  src/pages/Survey/index.tsx
  src/pages/SurveyResult/index.tsx
  src/routes/RouteDef.tsx
Labels: ✨ Feat, 🎶 wontfix

#40 Feat: 도서관리 api 매핑
  src/pages/Admin/CreateBookList/index.tsx
  src/pages/Admin/ManageBookList/index.tsx
  src/pages/Admin/UpdateBookList/index.tsx
  src/routes/RouteDef.tsx
Labels: ✨ Feat, 🎶 wontfix

#57 Fix: 자녀 프로필 상세보기 페이지 수정
  src/pages/MyPage/index.tsx
  src/pages/MyPageDetailChildProfile/index.tsx
Labels: 🛠️ Fix

#47 Feat: 로그인 모달 UI 구현
  package-lock.json
  package.json
  src/modal/LoginModal.tsx
  src/pages/Main/index.tsx
Labels: ✨ Feat

#60 Feat: 로그인/회원가입/중복체크 API 매핑 및 토큰 관련 로직 구현
  src/axiosWithToken.ts
  src/pages/Login/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/SignUp/index.tsx
  src/pages/Survey/index.tsx
Labels: ✨ Feat, 🎶 wontfix

#63 Feat: 현재 진행중인 이벤트 조회 및 참여 요청 API 매핑
  src/pages/Event/index.tsx
  src/pages/Main/index.tsx
Labels: ✨ Feat

#66 Feat: 관리자 페이지 토큰 적용
  src/pages/Admin/CreateBookList/index.tsx
  src/pages/Admin/ManageBookList/index.tsx
  src/pages/Admin/UpdateBookList/index.tsx
Labels: ✨ Feat, 🎶 wontfix

#72 Feat: 메뉴 접근 제한 구현
  src/pages/Main/index.tsx
Labels: ✨ Feat, 🎶 wontfix

#73 Refactor: 자녀 프로필 관련 API 인증 사용자 반영
  src/pages/MyPage/index.tsx
  src/pages/MyPageCreateChildProfile/index.tsx
  src/pages/MyPageDetailChildProfile/index.tsx
  src/pages/MyPageEditUserProfile/index.tsx
  src/pages/MyPageManageChildProfile/index.tsx
Labels: 🚀 Refactor

#74 Feat: 메인페이지 기본 추천 연동
  src/main.tsx
  src/pages/Main/index.tsx
Labels: ✨ Feat

#71 Refactor: 도서 상세 좋아요/싫어요 토큰 적용
  src/pages/BookDetail/index.tsx
  src/pages/BookList/index.tsx
Labels: 🚀 Refactor

#75 Refactor: 좋아요 상태 반영
  src/pages/BookDetail/index.tsx
Labels: 🚀 Refactor

#78 Fix: 좋아요 상태 버그 수정
  src/pages/BookDetail/index.tsx
Labels: 🛠️ Fix, 🎶 wontfix

#76 Feat: mbti에 허깅페이스 적용한 후 도서 등록 및 삭제되도록 구현후 API 매핑
  src/pages/Admin/CreateBookList/index.tsx
  src/pages/Admin/UpdateBookList/index.tsx
Labels: ✨ Feat, 🎶 wontfix
