Repository KKUMTEUL/KKUMTEUL-frontend, pull requests merged in 2024-11, with the labels that each got.

#82 Refactor: kkumteul UI 2차 수정-2
  fonts.d.ts
  public/assets/cookie.png
  public/assets/topic/wish.png
  src/components/survey/Interest.tsx
  src/font/RecipekoreaFont.ttf
  src/modal/EventModal.tsx
  src/pages/BookList/index.tsx
  src/pages/EventInfo/index.tsx
  src/pages/EventTicket/index.tsx
  src/pages/Main/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPageCreateChildProfile/index.tsx
  src/pages/MyPageEditUserProfile/index.tsx
  src/pages/MyPageManageChildProfile/index.tsx
  src/pages/Survey/index.tsx
  src/pages/SurveyResult/index.tsx
  src/routes/RouteDef.tsx
  src/styles/globalStyles.ts
Labels: 🚀 Refactor

#83 Refactor: 이벤트 결과 UI 구현 및 API 매핑
  src/modal/EventResultModal.tsx
  src/pages/Main/index.tsx
Labels: 🚀 Refactor

#84 Refactor: 이벤트 결과 모달 스크롤 가능하도록 수정
  src/modal/EventResultModal.tsx
Labels: 🚀 Refactor

#85 Feat: 이벤트 참여 완료 모달 구현
  src/modal/EventJoinCompleteModal.tsx
  src/pages/EventInfo/index.tsx
  src/pages/Login/index.tsx
Labels: 🚀 Refactor

#80 Refactor: 검색어 기능 및 페이지네이션 리팩토링
  src/pages/Admin/ManageBookList/index.tsx
Labels: 🛠️ Fix, 🚀 Refactor

#86 Fix: 관리자 페이지 필터 기능 수정
  src/pages/Admin/ManageBookList/index.tsx
Labels: ✨ Feat, 🎶 wontfix

#87 refactor: 좋아요/싫어요 상태 알림 모달
  src/pages/BookDetail/index.tsx
Labels: 🚀 Refactor
